package no.kristiania.yatzy;


public enum YatzyCategory {
    TWOS, THREES, FOURS, FIVES, SIXES, PAIR, TWOPAIRS, FULLHOUSE, SMALLSTRAIGHT, LARGESTRAIGHT, FOUROFAKIND, THREEOFAKIND, CHANCE, YATZY, ONES
}
